- .github/workflows/deploy_vercel.yaml
- package.json
- pnpm-lock.yaml
- scripts/clone.cjs
- tsconfig.json
For some reason, the build process occasionally fails when attempting to clone the data repository. To address this, I added a post-build step to clone the data repository before the build begins.
> Feat: add script to clone data repository

- README.md
- Add detailed tech stack and project structure
- Include CMS and content management details
- Add configuration and environment setup guides
- Update deployment and development instructions
> [docs]: Enhance README with comprehensive project Documentation and Setup guides

- app/[locale]/providers.tsx
- app/api/auth/[...nextauth]/error-handler.ts
- app/api/auth/[...nextauth]/error-wrapper.ts
- app/api/auth/[...nextauth]/route.ts
- app/global-error.tsx
- auth.config.ts
- components/error-boundary.tsx
- components/error-provider.tsx
- drizzle.config.ts
- lib/api/error-handler.ts
- lib/auth/error-handler.ts
- lib/auth/index.ts
- lib/db/drizzle.ts
- lib/db/queries.ts
- lib/lib.ts
- lib/repository.ts
- lib/utils/error-handler.ts
- lib/utils/index.ts
- package.json
- pnpm-lock.yaml
- scripts/check-env.js
- scripts/clone.cjs
- Add comprehensive error handling utilities and components
- Create error boundary for client-side error capture
- Implement graceful OAuth configuration validation
- Add environment variable validation at startup
- Fix NextAuth provider errors with proper error messages
- Create standardized API error responses
- Add global error page for server-side errors
- Integrate error handling in authentication flow
> [Feat]: Implement global error handling system

- lib/auth/services/supabase.service.ts
- lib/db/queries.ts
Implement a database query function to retrieve a user by their ID.
This function will throw an error if the user is not found, ensuring
proper error handling for user lookups.
> [Feat]: Add getUserById database query function

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci.yml
- components/header/ThemeSwitch.tsx
- Implements CI workflow that runs on pushes to main and develop branches
- Adds linting and type checking steps
- Configures build process with environment variables
- Verifies build successadd bots suggestions
> [Feat]: add GitHub Actions CI workflow for build and lint checks

- package.json
- scripts/clone.cjs
> Fix: content repository cloning logic

- app/[locale]/items/[slug]/page.tsx
- components/item-detail/breadcrumb.tsx
- components/item-detail/item-detail.tsx
- components/item-detail/item-icon.tsx
- Improve visual appearance of item components in both light and dark modes
- Remove excessive shadows for cleaner interface
- Optimize ItemIcon component with better color transitions
- Refine card styling for better consistency across themes
- Prepare layout structure for future sidebar implementation
https://github.com/user-attachments/assets/475d232e-c965-4487-bbfb-513a00698a19
1. 
2. 
3.
> Feat(ui): Enhance item detail page design

- components/language-switcher.tsx
https://github.com/user-attachments/assets/9cbc5aad-8410-4e98-96d4-28130110691a
1. 
2. 
3.
> [Fix]: build error on Vercel (ever-works-website-template)

- app/[locale]/(listing)/globels-client.tsx
- components/home-two/home-two-layout.tsx
- hooks/use-sticky-state.ts
> [Feat]: Sticky filter enhancement

- app/[locale]/(listing)/listing.tsx
- app/[locale]/globals.css
- components/filters.tsx
- components/scroll-to-top-button.tsx
- hooks/use-scroll-to-top.ts
> [Feat]: Scroll to top pagination

- app/[locale]/items/[slug]/page.tsx
- components/item-detail/share-button.tsx
- messages/en.json
> [Fix]:build

- app/[locale]/pricing/page.tsx
- app/[locale]/submit/page.tsx
- components/hero.tsx
- Reduce unnecessary vertical padding and margins
- Improve content density while maintaining readability
- Optimize layout for better space utilization
- Maintain responsive design across all screen sizes
1. 
2. 
3.
> Refactor(hero): optimize vertical spacing in hero component

- app/[locale]/categories/listing-categories.tsx
- components/hero.tsx
- components/home-two/home-two-categories.tsx
- components/home-two/home-two-filters.tsx
- components/items-categories.tsx
- components/pricing/pricing-section.tsx
- Fix slow rendering and console errors
- Optimize vertical spacing to prevent wasted space
- Fix category display truncation issues
- Add Show all link for categories list
- Align categories behavior with tags functionality
- Improve overall page performance
1. 
2. 
3.
> Fix(categories): Improve categories page performance and UX

- app/[locale]/categories/listing-categories.tsx
- components/home-two/home-two-filters.tsx
- Remove horizontal scrolling for categories list
- Show only categories that fit in one line
- Add Show all button to expand full list
- Align UX with tags page implementation
- Improve mobile responsiveness
1. 
2. 
3.
> refactor(categories): harmonize categories

- lib/content.ts
- Add ContentConfig interface for centralized configuration management
- Add PRUpdate interface for PR-related settings
- Update PagingMode type to match config.yml values
- Integrate new configuration parameters:
- max_search_queries
- max_results_per_query
- max_pages_to_process
- relevance_threshold_content
- min_content_length_for_extraction
- ai_first_generation_enabled
- prompt_comparison_confidence_threshold
- Set default pagination mode to 'paging'
1. 
2. 
3.
> [Feat]: integrate new config.yml parameters into content types

- app/[locale]/tags/listing-tags.tsx
- components/directory/details-form.tsx
- components/filters.tsx
- components/footer/footer-link-group.tsx
- components/footer/social-link-item.tsx
- components/header/ThemeSwitch.tsx
- components/layout-switcher.tsx
- components/tags-items-column.tsx
- components/theme-toggler.tsx
- lib/theme-color-manager.ts
- lib/themes.tsx
> [Chore]: Improve Dynamic theme color

- components/ui/infinity-scroll.tsx
- package.json
- pnpm-lock.yaml
- Add custom useInfiniteScroll hook for better state management
- Implement error handling with retry functionality
- Create reusable LoadingIndicator and ErrorState components
- Add TypeScript interfaces for better type safety
- Improve component organization and maintainability
- Add translations for all UI states
- Optimize performance with useCallback and memoization
- Support external state management
1. 
2. 
3.
> [Feat]: Enhance infinite scroll component with professional architecture

- components/filters.tsx
> [Fix]: Improve Tag Selection in Dynamic Theme Color System

- components/ui/select-pagination-type.tsx
- Add TypeScript types and interfaces
- Implement controlled/uncontrolled component pattern
- Extract icons and configuration to constants
- Add accessibility attributes (aria-pressed, aria-label)
- Implement proper disabled state handling
- Use cn utility for conditional classNames
- Add component documentation
1. 
2. 
3.
> Feat(UI): improve SelectPaginationType component

- components/layout-switcher.tsx
- components/shared-card/index.tsx
- components/ui/select-pagination-type.tsx
> [Feat]: Dynamic pagination mode switching

- components/footer/footer-bottom.tsx
- components/footer/footer-link-group.tsx
- components/footer/index.tsx
- components/footer/social-links.tsx
> [Feat]: Footer navigation cleanup

- components/context/LayoutThemeContext.tsx
- components/header/ThemeSwitch.tsx
- hooks/use-theme.ts
- lib/theme-color-manager.ts
- lib/theme-utils.ts
- lib/themes.tsx
> [Fix]: Remove duplicate modern theme

- app/[locale]/layout.tsx
- components/directory/details-form.tsx
- components/directory/input-link.tsx
- components/payment/flow-selector-modal.tsx
- components/pricing/plan-card.tsx
- components/pricing/pricing-section.tsx
- Simplify complex CSS classes in payment flow selector modal
- Reduce button styling complexity in directory components
- Streamline pricing section and plan card styles
- Remove excessive gradients and animations for cleaner design
- Improve dark/light mode consistency across components
- Reduce CSS line count by 46 lines for better maintainability
1. 
2. 
3.
> refactor: simplify UI component styles and improve maintainability

- components/favorite-button.tsx
- components/item-detail/comments-section.tsx
- hooks/use-comments.ts
- hooks/use-pricing-section.ts
- lib/db/migrations/0000_flowery_whirlwind.sql
- lib/db/migrations/meta/0000_snapshot.json
- Add authentication verification before commenting, rating, and deleting comments
- Implement auth check before adding items to favorites
- Add auth verification before proceeding with payment checkout
- Replace error toasts with automatic login modal opening for better UX
- Improve API error handling with centralized 401/Unauthorized detection
- Update use-comments hook with proper authentication flow
- Enhance favorite-button with login modal integration
- Update pricing section to require authentication before checkout
1. 
2. 
3.
> [Feat]: Add authentication checks for comments, favorites, and payments

- app/api/lemonsqueezy/reactivate/route.ts
- lib/payment/lib/providers/lemonsqueezy-provider.ts
> Feat(api): add endpoint to reactivate LemonSqueezy subscriptions

- auth.config.ts
- lib/db/migrations/0033_friendly_gorgon.sql
- lib/db/migrations/meta/0033_snapshot.json
- lib/db/migrations/meta/_journal.json
- lib/db/queries.ts
- lib/db/schema.ts
- lib/payment/guards/feature.guard.tsx
- Fix React Hook useMemo missing dependency warning in FeatureGuard
- Simplify useMemo dependencies array for better performance
- Add clientId field to activityLogs table for client activity tracking
- Ensure clean build and linting
1. 
2. 
3.
> [Fix]: Resolve ESLint useMemo dependency warning and add clientId to activityLogs

- app/api/admin/dashboard/stats/route.ts
- components/admin/admin-stats-overview.tsx
- hooks/use-admin-stats.ts
- lib/db/migrations/0032_add_is_admin_to_roles.sql
- lib/db/schema.ts
- lib/repositories/admin-stats.repository.ts
Refactors admin dashboard hook to replace mock data with real API calls, implementing comprehensive error handling and proper data transformation from repository to frontend.
- Resolves admin dashboard static data issue
- Implements real-time data flow for admin statistics
This PR completes the admin dashboard integration by replacing the static mock data with dynamic API calls to the database. The `useAdminStats` hook now fetches real-time statistics from `/api/admin/dashboard/stats`, providing administrators with accurate, up-to-date information about users, submissions, activity, and newsletter subscriptions.
The implementation includes robust error handling with retry logic, proper loading states, and type-safe data transformation from the repository layer to the frontend components. …
> feat(admin-dashboard-integration): Admin Stats Hook Refactor (phase 3)

- lib/background-jobs/config.ts
- lib/background-jobs/index.ts
- lib/background-jobs/job-factory.ts
- lib/background-jobs/local-job-manager.ts
- lib/background-jobs/types.ts
- scripts/check-env.js
Implements a background job manager abstraction layer with optional Trigger.dev support, enabling environment-based switching between local scheduling (development) and Trigger.dev (production) for background processes.
- Resolves: Sub-ticket 1 - Create Background Job Manager Abstraction Layer
- Related to: Main Epic - Implement Conditional Trigger.dev Support for Background Jobs
This PR establishes the foundation for reliable background job processing by creating an abstraction layer that allows the application to use local scheduling in development and Trigger.dev in production when properly configured. The implementation provides a clean interface for job scheduling while maintaining backward compatibility with existing services.
**Problem Solved:**
- Current background processes use …
> feat: add background job manager abstraction layer

- app/[locale]/(listing)/globals-client.tsx
- app/[locale]/admin/comments/page.tsx
- hooks/use-admin-comments.ts
- Add useAdminComments hook with React Query integration
- Refactor admin comments page to use custom hook
- Integrate with server-client-api for API calls
- Add proper TypeScript types and error handling
- Improve code organization and reusability
- Fix GitHub authentication for categories CRUD operations
- Update DATA_REPOSITORY URL to correct organization
1. 
2. 
3.
> feat: create custom hooks for admin comments management

- app/[locale]/admin/roles/page.tsx
- hooks/use-admin-roles.ts
- Add useAdminRoles hook with React Query integration
- Refactor admin roles page to use custom hook
- Integrate with server-client-api for API calls
- Add proper TypeScript types and error handling
- Improve code organization and reusability
- Fix type casting issues for RoleData compatibility
- Remove unused imports and variables
1. 
2. 
3.
> feat: create custom hooks for admin roles management

- app/[locale]/admin/layout.tsx
- components/profile-button/index.tsx
- components/profile-button/logout-button.tsx
- components/profile-button/menu-items.tsx
- components/profile-button/profile-menu.tsx
Fixes long loading gaps in the profile button navigation by implementing immediate menu closure and proper loading states
throughout the user interface flow.
Addresses issue with long loading gap time in profile button navigation
The profile button was experiencing long loading gaps during navigation, causing poor user experience. Users would click
menu items but see no immediate feedback, leading to confusion about whether their action was registered.
This PR implements a comprehensive solution by:
1. Removing the blocking admin panel loading screen that was causing delays
2. Adding navigation state management to provide immediate visual feedback
3. Implementing proper loading overlays with backdrop blur for better UX
4. Converting Link-based navigation to button-based navigation with …
>  fix: improve profile button loading states and navigation UX

- app/[locale]/admin/categories/page.tsx
- components/admin/users/user-form.tsx
- hooks/use-admin-categories.ts
- Create custom hook with React Query and server-client API
- Refactor admin categories page to use new hook
- Remove manual state management and API calls
- Add TypeScript types and error handling
1. 
2. 
3.
> feat: add useAdminCategories hook and refactor categories page

- app/api/lemonsqueezy/webhook/route.ts
- docs/LEMONSQUEEZY_WEBHOOK_SETUP.md
- Add complete webhook endpoint at /api/lemonsqueezy/webhook
- Implement HMAC SHA-256 signature verification for security
- Map LemonSqueezy events to generic webhook event types
- Add support for subscription lifecycle events (created, updated, cancelled)
- Handle payment events (succeeded, failed, refunded)
- Integrate with existing WebhookSubscriptionService
- Add automatic email notifications for payment confirmations
- Include comprehensive error handling and logging
- Use singleton pattern for LemonSqueezy provider initialization
- Add complete documentation and setup guide
Supported events:
- subscription_created, subscription_updated, subscription_cancelled
- subscription_payment_success, subscription_payment_failed
- subscription_trial_will_end
- order_created, order_refunded …
> feat: implement LemonSqueezy webhook handler with full event support

- hooks/use-admin-comments.ts
- hooks/use-admin-featured-items.ts
- hooks/use-admin-items.ts
- hooks/use-admin-notifications.ts
- hooks/use-admin-roles.ts
- hooks/use-admin-users.ts
- hooks/use-current-user.ts
- hooks/use-featured-items-client.ts
- lib/query-client.ts
Optimizes React Query configuration and polling intervals to reduce API request frequency by ~90%, resolving 20+ second
response times for `/api/auth/session` and eliminating excessive polling across admin components.
This PR addresses critical performance issues caused by aggressive API polling throughout the application. The main
problems were:
1. **Excessive session validation**: `/api/auth/session` called 20+ times with 22+ second response times
2. **Aggressive admin polling**: Multiple admin hooks polling every 30 seconds
3. **Notification spam**: Notifications API called 9 times with 30-second intervals
4. **Inconsistent React Query config**: Conflicting cache settings causing unnecessary refetches
The solution implements request deduplication through optimized React Query …
> fix: perf: reduce notification polling from 30s to 5min intervals

- .env.example
- components/context/LayoutThemeContext.tsx
- Add memoization for currentTheme and contextValue
- Implement safe localStorage with error handling
- Add validation functions for all state types
- Include isInitialized state for better UX
- Add utility functions (resetToDefaults, clearStorage)
- Improve type safety with type guards
- Optimize re-renders with proper useCallback usage
1. 
2. 
3.
> [Feat]: Optimize LayoutThemeContext

- app/[locale]/docs/docs-page-content.tsx
- components/footer/social-links.tsx
- components/header/index.tsx
- public/openapi.backup.json
- public/openapi.json
- yarn.lock
- Updated dependency versions for @heroui/input, @heroui/system, and @heroui/theme in yarn.lock.
- Refactored DocsPageContent component for improved layout and responsiveness.
- Updated footer social links to use translated titles.
- Removed static API Docs link from header navigation.
https://github.com/user-attachments/assets/e0ae03b2-9fed-4c61-955e-6a3d5808678e
> Fix: Page Alignment

- app/[locale]/categories/listing-categories.tsx
- hooks/use-admin-items.ts
- hooks/use-admin-tags.ts
- Fix API response structure mismatch in use-admin-tags hook
- Update getTags method to access response.data.data instead of response.data
- Adapt createTag and updateTag methods to handle correct API response format
- Resolve issue where tags data was not displaying in admin interface
1. 
2. 
3.
> fix: correct tags data display in admin panel

- app/[locale]/(listing)/globals-client.tsx
- app/[locale]/globals.css
- app/layout.tsx
- components/header/index.tsx
- components/home-two/home-two-categories.tsx
- components/layouts/LayoutMasonry.tsx
- components/ui/animations.tsx
- components/ui/auth-illustrations.tsx
- components/ui/password-strength.tsx
- components/ui/responsive-container.tsx
- hooks/use-detail-form.ts
- lib/payment/config/lemonsqueezy-variants.ts
- lib/payment/lib/payment-provider-factory.ts
- lib/payment/ui/stripe/stripe-elements.tsx
- Add responsive breakpoints system across header, cards, and layouts
- Implement conditional visibility with hidden classes for different screen sizes
- Optimize mobile experience with compact spacing and adaptive elements
- Enhance desktop layout with sticky sidebar and expanded features
- Reduce gaps between sidebar and content for better space utilization
- Add progressive masonry layout with 5 responsive breakpoints
- Improve typography scaling from mobile to ultra-wide screens
- Add hover effects and animations only on desktop for performance
1. 
2. 
3.
> feat: Enhance responsive design with adaptive breakpoints and conditional visibility

- app/[locale]/items/[slug]/page.tsx
- components/item-detail/index.ts
- components/item-detail/item-detail.tsx
- components/item-detail/server-item-content.tsx
- Create ServerItemContent component to handle MDX rendering on server
- Update ItemDetail component to accept pre-rendered content as prop
- Move MDX rendering from Client Component to Server Component
- Fix MDXRemote is an async Client Component error
1. 
2. 
3.
> fix: resolve MDXRemote async Client Component error

- .env.example
- app/[locale]/items/[slug]/opengraph-image.tsx
- app/[locale]/items/[slug]/page.tsx
- app/[locale]/layout.tsx
- app/layout.tsx
- app/opengraph-image.tsx
- app/robots.ts
- components/footer/brand-link.tsx
- components/footer/social-links.tsx
- components/item-detail/item-detail.tsx
- lib/config.ts
- lib/seo/schema.ts
> feat: Improve basic SEO
